tesourohq/Tesouro-Github-Actions

build-docker-images/action.yml
Motivation
---
To create Liquibase docker image, we need to specify context folder to `build-docker-images`. This field is currently hard-coded.
Modifications
---
Added `docker-context` input parameter
Results
---
We should be able to build image for any other docker file in a repo
=> (PAYM-906) Added `docker-context` to `build-docker-images` action

functional-tests/action.yml
Motivation
---
Functional test reports were not being generated when failure occurs
Modifications
---
Added when: always() to git action
Results
---
Should now always produce report
=> (PAYM-1010) Adding always to reports for functional tests

build-docker-images/action.yml
Motivation
---
- I want to keep latest up to date on our GCR repositories
Modifications
---
- Updated the GitHub Action to add a latest tag when on main
Results
---
- You'll now get a latest tag on main
Example from a PR build
=> (PAYM-1033) Update GitHub Action to Publish Latest on Main

build-and-test/action.yml, build-docker-images/action.yml
Motivation
---
The upgraded projects to .NET 7 break.
Modifications
---
Added an input variable to pass .NET version if needed.
Temporarily removed support for emulated arm64 images
Results
---
This action should work both for existing and projects upgraded to .NET 7
=> (PAYM-1073) Add a parameter for .NET version

build-docker-images/action.yml, get-version/action.yml
Motivation
---
- I want the built containers to specify their version in the built assembly
- In order to do this, I need to pass in the ASSEMBLY_VERSION
- This means updating the version stuff to output the assembly version as well as requiring it as input
Modifications
---
- Updated build args to include ASSEMBLY_VERSION
- Updated the version to include AssemblySemVer as an output
Results
---
Now, as part of our docker file, we can do something like this
```
ARG ASSEMBLY_VERSION
WORKDIR "/src/Tesouro.Payments.Service.CardProcessing"
RUN dotnet build "Tesouro.Payments.Service.CardProcessing.csproj" -c Release -o /app/build /p:AssemblyVersion=${ASSEMBLY_VERSION}
```
=> (PAYM-1487) Update Build Action to support passing in assembly version

build-and-test/action.yml
Motivation
I want the action to continue even if there is a failure on the attempt to a nuget source.
Modifications
Added `|| true` to the end of the bash command.
Results
It was updated.
=> ignore failure to add nuget source.

armory-deploy/action.yaml, armory-deploy/example-armory-deployment.yaml, armory-deploy/example-job.yaml, build-docker-images/action.yml
Motivation
I want to add a common action for using Armory CDaaS, that will bake manifests and deploy using Armory.
Modifications
I added the action.
NOTE: As a part of this merge I am going to make a new release under "v8"
=> (PAYM-1491) - Add a ci armory deploy action

functional-tests/action.yml
Motivation
---
- We discovered that about half the runner space was being used by tons of images and volumes remaining
- This change aims to automatically prune images & volumes after the functional test
Modifications
---
- Updated the functional test dispose to remove rmi and volume
Results
---
- Should use MUCH less space over time
=> (PAYM-1809) Upgrade to Automatically Prune After Functional Test

armory-deploy/action.yaml
Motivation
---
We need to add some non-mandatory inputs to the Armory deploy action in order to make it more flexible (in particular, for Frontend deployments)
Modifications
---
- armory action inputs
Results
---
- for builds already using the action, nothing should change
=> (PAYM-1795) Armory-deploy inputs

build-and-test/action.yml
Motivation
---
With .NET 7.0 official release, we don't need prerelease SDK builds
Modifications
---
* Set `include-prerelease` flag to false
Results
---
Builds should be only using official release versions
=> (PAYM-2045) Set `include-prerelease` flag to false

functional-tests/action.yml
Motivation
---
- So, first, I was chasing this whole thing with trying to nuke junit & swagger and then I realized.... this is all because I keep using the same compose name. I had erroneously thought this would help with rebuilding and saving time, but it really does nothing in that regard and only helps with keeping volumes/etc. around.
- So, now, I just want to have a new label for each workflowid/runid
Modifications
---
- Updated our functional tests to use a new workflowid/runid based label
Results
---
- No more volume matches shenanigans for the "_test_1" container :-)
=> (PAYM-2102) Update Functional Test Runner to use variant compose labels

functional-tests/action.yml
This reverts commit 8f96e26caa298fe5df77db63783dbc8206bc3fc9.
Motivation
---
- This won't work actually
Modifications
---
- Revert last change
Results
---
- Variables are different in context so github.run_number won't always exist :(
=> (PAYM-2102) Revert Update Functional Test Runner to use variant compose labels

functional-tests/action.yml
Motivation
---
Allow the functional test phase of the start the correct pact generator image.  Merging this is required before merging https://github.com/tesourohq/Tesouro.Payments.Service.PaymentProcessing/pull/263
Modifications
---
* Altered the functional test action to accept a new optional parameter `pacts-image-name` that if supplied will be made available in the environment so that the functional test job in the payment processing workflow can start the correct docker container that contains the pacts for this commit.
Results
---
When running the compose-up for the functional tests:
```
Pulling pact-generator (gcr.io/tesouro-cloud/tesouro-service-payment-processing-pacts-ci:1.0.218-pr-0263.10)...
1.0.218-pr-0263.10: Pulling from …
```
=> Make the pacts image location available to the compose file environment

functional-tests/action.yml
Motivation
---
- I'm sooooooooooooooooooooooooooooooooooooooooo sick and tired of file permission errrors
- I want to nuke junit.xml & swagger.json from our repositories
Modifications
---
- Updated the functional test script to both PRE and POST nuke the bin/results folder/files
- Updated the docker compose name to be variant for networking purposes
Results
---
- The bin/results should be empty/nuked/destroyed both before and after running tests
https://tesouro.atlassian.net/browse/PAYM-2138
=> (PAYM-2138) Pre & Post Nuking of test/tests/bin/results

functional-tests/action.yml
Motivation
---
- I'd like to always nuke the files after functional tests run
Modifications
---
- Updated the clean up results action to always run
Results
---
- We will always nuke the associated results directly
https://tesouro.atlassian.net/browse/PAYM-2147
=> (PAYM-2147) Add `always()` to "Clean Up Results"

functional-tests/action.yml
Motivation
---
Supply as much information as possible to the pact broker during provider verification
Modifications
---
* Provide an optional input for the PACT_BROKER_TOKEN
* Make the version, token and branch available in the environment
Results
---
From the profile service run output, we can see the PACT_BROKER_TOKEN, PROVIDER_APP_VERSION and GIT_BRANCH are all available in the environment for the test's docker compose ci file
```
Run # Build test container and associated services (and run tests)
export CLOUDSDK_PYTHON=python2
docker-compose -f docker-compose.ci.yml -p test_ci-functional-tests up --build --force-recreate -d
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/ubuntu/actions-runner/_work/Tesouro.Users.Service.Profi …
```
=> (PAYM-2058) - implement provider verification for profile service receiving call from payment processing

functional-tests/action.yml
Motivation
---
When something goes wrong with the functional tests, I'm often left wondering what.  This needs to be merged to main at the same time as this [Payment Processing PR](https://github.com/tesourohq/Tesouro.Payments.Service.PaymentProcessing/actions/runs/3659442902)
Modifications
---
* Save the container logs for all of the applications running and make them available as a build artifact that can be downloaded and used for debugging issues.
* I also used this PR to address the ARM runner issue by downloading the pact file artifact created by the PaymentProcessing build
Results
---
From the [Payment Processing PR](https://github.com/tesourohq/Tesouro.Payments.Service.PaymentProcessing/actions/runs/3659442902) that is tied to this at the hip:
=> (PAYM-2270) - Save Functional Test Container Logs

armory-deploy/action.yaml
Motivation
I want to bake and use the stage manifests, to deploy to the stage environment.
Modifications
I added inputs for the stage manifests.
NOTE:
- Tag this change BEFORE merging it to main.
- Adjust the applications one at a time to use the new tag, in place of @main.
- The new tag is `@stage-deploy-update`
- Each microservice will need to have the full stage-deployment pattern implemented first, with stage manifests/overlays and SecretProviderClass objects, and AWS updates.
- Once they are ALL converted, merge to main.
- Adjust the applications one at a time, again, back to using @main.
That way this doesn’t cause a breaking change for all the microservices.
=> Add stage manifest inputs and bake step.

create-sdk/action.yml
Motivation
In case a ticket is closed after GitHub actions runs and then is reopened this will hopefully skip the 409 from nuget
Modifications
added skip duplicate option to nuget add source
Results
hopefully actions run!
=> (PAYM-2449) add skip duplicate to create sdk action

package-and-publish/action.yml
Motivation
In order to ignore 409 errors on duplicates you can pass this option
Modifications
added --skip-duplicate to push
Results
we can push!
=> (PAYM-2450) add skip duplicate to package and push action

armory-deploy/action.yaml
Motivation
* I want the armory agent to track main, so it picks up the most recent updates.
Modifications
* I adjusted the reference to `@main`
* I added the new flag to wait for deployments to succeed.
Results
* The armory action should now track the most recent changes.
=> Update armory action version.

functional-tests/action.yml
Motivation
---
Provide pact verification results in our build and fail if we shouldn't deploy
Modifications
---
* The existing functional test reporter uses jest-junit format, which can't parse the output of pact's junit xml.
Results
---
Used in BillingAccounting [PR40](https://github.com/tesourohq/Tesouro.Payments.Service.BillingAccounting/actions/runs/4376737536/jobs/7659368542)
Proof that it's safe for repositories that don't specify [pact-provider-verification](https://github.com/tesourohq/Tesouro.Payments.Service.BillingAccounting/actions/runs/4378023640/jobs/7662268783)
=> (PRODEV-1163) - Report provider results with a different reporter

armory-deploy/action.yaml
Motivation
---
- I'd like to be able to get the staging and production database rollouts separated
Modifications
---
- Added two optional parameters for the stage and prod migrations
- Added two optional parameters for the stage and prod migration paths
Results
---
- We can now use this version of the action to build stage and production manifests (and roll out that way)
=> (PRODEV-1389) Update to allow database migration kustomize builds

.gitignore, contract-requiring-verification-published/action.yml
Motivation
---
Provide an action that can be invoked by webhooks that can be fired by the pact broker when a pact changes.
Modifications
---
New action is available that runs pact provider verification with a pact located from a url.  The body looks something like this after substitutions:
```json
{
"event_type": "contract_requiring_verification_published",
"client_payload": {
"pact_url": "https://tesouro.pactflow.io/pacts/provider/billingaccounting_service/consumer/funding_service/version/0.1.30",
"consumer_name": "funding_service",
"consumer_version_number": "0.1.30",
"consumer_branch": "main",
"sha": "d4dc1c1687cd8fd9022426062b9b9b277ad8018b",
"provider_branch": "gregtest",
"provider_version_number": "0.1.52-pr-0055.1",
"message": "Verify changed pact for billingaccounting version …
```
=> (PAYM-1274) - pact provider verification on pact changed webhook

armory-deploy/action.yaml
Motivation
---
* I want to secure the actual deployment process for any microservice that calls this action to ONLY deploy from the main branch (on a merge to main).
Modifications
---
* I added a conditional check for the main branch to the deploy step.
Results
---
* Even if an application workflow attempts to call armory-deploy off a branch other than main, this should prevent it from actually deploying.
=> (PRODEV-1432) - Lock armory-deploy deployment step to main branch only.

armory-deploy/action.yaml
Motivation
---
I want the stage manifests to be optional as a parameter, so we can use this action more flexibly.
Modifications
---
* I made the stage-manifest-path input optional, and added a check to only execute the step for baking them if a value is passed in.
Results
---
* The action will now bypass baking the stage manifests if nothing is passed in.
* This also, however will fail if the armory-deployment configuration that is passed in tries to reference stage manifests, which will no longer be there.
=> (PRODEV-2003) - Make stage manifests optional for armory-deploy.

argocd-deploy/action.yaml
Motivation
---
Need a way to apply a unique version and deploy via ArgoCD.
Modifications
---
I added an action template to apply the github.sha of the triggering workflow as the deployment version. Then it initiates a deployment sync for the calling app.
Results
---
MVP of ArgoCD app deployment (sync) action.
=> [PRODEV-1896] GitHub action for argo deployment

argocd-deploy/action.yaml
Motivation
---
Deploying with the github sha wasn't working. It also wasn't going to be unique for action re-runs.
Modifications
---
Switched github sha for github run-attempt.
Results
---
Unique deployment versions per run attempt
=> [PRODEV-2089] semver . run_attempt for unique deployment version

argocd-deploy/action.yaml
Motivation
---
It's a headache to risk an infinite action loop by running a versioning commit on main in an action.
Modifications
---
Merge into release branch with versioning commit.
Results
---
A deployment branch that reflects actual deployment state.
=> [PRODEV-2105] Add sha back to version, commit to release branch

functional-tests/action.yml
Motivation
---
tired of seeing Github Actions step named Integration Tests when it should be Functional Tests
Modifications
---
renamed Integration to Functional
Results
---
=> (PRODEV2095) - rename step from Integration tests to Functional tests

functional-tests/action.yml
Motivation
---
When the functional tests fail for unexpected reasons, I want the docker logs.
Modifications
---
just an `always` flag on this step
Results
---
even when the docker test container fails with an exit code of 1, we get the docker logs as in this [result](https://github.com/tesourohq/Tesouro.Payments.Service.CoreTransaction/actions/runs/5360134830)
=> (PRODEV-2289) - better debugging when actions fail

argocd-deploy/action.yaml
Motivation
---
We were relabeling our DB migration job with a deprecated and unnecessary label. We also have refactored our other labels to have a [0] false selector entry so our semver label can be generated there.
Modifications
---
- Remove unnecessary/deprecated job app label. 
- Add label for stage manifests.
- Move semver to [0] array entry.
Results
---
Cleaner and more durable deployments!
=> (PRODEV-2960) Small refactor

contract-requiring-verification-published/action.yml
Motivation
---
- We'd like our pact verifications to work correctly
- We need the GH_PACKAGES_TOKEN in order to properly install certain packages
Modifications
---
- Added GH_PACKAGES_TOKEN as a param
- Passed GH_PACKAGES_TOKEN into docker-compose.ci.yml
Results
---
- Pact verification should work now
=> (PRODEV-4305) Add GH_PACKAGES_TOKEN to pact verification

build-docker-images-ecr/action.yml
Motivation
---
If image output is GCR our pipelines will continue to use that. It's time to flip the switch.
Modifications
---
Changed image-name output to use the ECR image-name.
Results
---
🚀
=> (PRODEV-4582) Change build image output to ECR.

build-and-test/action.yml, package-and-publish/action.yml
Motivation
---
- We want the latest SDK for all our actions by default
Modifications
---
- Update commands to default to latest SDK
Results
---
- This really doesn't change anything since nearly ALL of our services override this command but I don't want `7.0.100` to exist in our code base
=> (PRODEV-4656) Update to latest SDK

build-docker-images-ecr/action.yml
NOTE: Merge this after all the permission updates have gone through.
Motivation
---
I want our images to be scanned for critical CVEs during CI, and for CI to fail when they are detected, so we can enforce resolution of these vulnerabilities as a part of development rather than in response to discovery. I also want a report of the scans to be posted for reference during resolution, and for auditing.
Modifications
---
I added image scanning, report-generation, and CI failure to the `build-docker-images-ecr` action.
Results
---
Images are now required to be free from critical CVEs before a PR can be merged.
=> (PRODEV-5010) - Add Image Scanning to CI

build-docker-images-ecr/action.yml
Motivation
---
I want to avoid being rate-limited by dockerhub.
Modifications
---
* We were avoiding it, except for the during the steps ABOVE where we auth, one of which (the qemu setup step) pulls an image. That was happening anonymously, and was subject to the 100/6hrs rate limit. So... I moved the auth above that.
Results
---
Should avoid the rate limit now.
"But Ben... the branch and ticket here say that you are going to add more details about how much quota we have left!"
"That's right, but you know what Dockerhub can't tell you if you are on a paid plan? You guessed it: your current quota usage. Oh they'll tell you if you are anonymous, or an individual, but if you are on a paid plan they just don't return that header to you, because it's a SECRET."
(In all seriousness, I put a …
=> (PRODEV-5264) - Shift Dockerhub auth to avoid rate limit

build-docker-images-ecr/action.yml
Motivation
---
Image scanning is consuming WAY too much Github Runner memory to be effective as a long term solution. It is blocking CI. We will research and implement a different tool soon, but need to remove it for now to unblock the pipeline.
Modifications
---
This just disables image scanning for the time being.
Results
---
CI is great again.
=> Disable image scanning for the time being

validate-federation/action.yml
Motivation
---
The supergraph diff as currently implemented fails on the merge queue. Will include a refactored diff with v3.
Modifications
---
- Removed supergraph diff.
Results
---
⚡ 👍
=> (PRODEV-5906) Remove Supergraph diff

build-docker-images-ecr/action.yml
Motivation
---
I want to stop pushing unnecessary stuff to ECR. ECR wrongly interprets this artifacts as "images" and they mess up our lifecycle rules and UI.
Modifications
---
I disabled the provenance metadata.
Results
---
No more pushes of that stuff to ECR.
=> (PRODEV-6088) - Stop pushing provenance metadata to ECR

validate-graphql/action.yml
Motivation
---
Workflow to handle graphql breaking changes.
Modifications
---
- Add fail-on-breaking-change toggle defaulting to true
- Add approve-label expected-breaking-graphql-change
Results
---
👍
=> (PRODEV-6736) Add breaking change workflows and toggle

build-and-test/action.yml
Motivation
---
https://tesourohq.slack.com/archives/C02FJBY4JJD/p1710875444744629 - if a solution had multiple projects - it would leave only the last one.
Modifications
---
Use the prefix option for test output rather than file.  Every file gets tagged with a timestamp so we don't eat them.
Results
---
https://github.com/tesourohq/Tesouro.Payments.Service.CoreTransaction/pull/424/checks?check_run_id=22851896651
=> (PRODEV-6721) Upload all the test project results - not just last one

argocd-deploy/action.yaml, build-docker-images-ecr/action.yml
Motivation
---
A flexible image versioning parameter that will work regardless of the number of dependent versioned images.
Modifications
---
- Added backwards compatible version images block, this appends an images block to the kustomize overlays leveraging the images transformer to apply versioning.
- Added backwards compatible image-name-without-tag output to our build action for later consumption in ArgoCD-Deploy.
Results
---
💪
=> (PRODEV-7239) Add N image versioning to ArgoCD Deploy action.

functional-tests-ecr/action.yml
Motivation
---
Fx tests are failing due to being unable to find a module due to case sensitivity. The test reporter sees these as skipped, not failed, so testing passes.
Modifications
---
Check exist code for tests and fail if need be
Results
---
consistent testing!
=> (PRODEV-7509)Check exit codes when running tests

validate-graphql/action.yml
Motivation
---
GraphQL inspector blows up on merge queue
Modifications
---
Add conditional to validate graphql action so it can only ever run on PR.
Results
---
🚀
=> (PRODEV-7834) GraphQL inspector blows up on merge queue

functional-tests-ecr/action.yml
Motivation
---
Currently, if your functional tests fail in CI you do not get the BDD or Pact Verification results reported in your action. Example here: https://github.com/tesourohq/Tesouro.Payments.Service.BillingAccounting/actions/runs/9271738881/job/25512846844
In this specific example, the BDD tests failed, but I was only able to verify that by downloading the docker logs and looking. We need to add the `always()` parameter to make sure a step is always executed. https://docs.github.com/en/actions/learn-github-actions/expressions#always
Modifications
---
* Add `always()` to functional test reporter steps
Results
---
We can see why tests failed in CI!
=> (PRODEV-8029) Always Report Functional Test Outputs

validate-federation/action.yml
Motivation
---
Exit with failure when rover fails to generate a supergraph.
Modifications
---
Explicitly run a status check against the docker exit codes of our rover builds.
Allow bypass with expected-breaking-federation-validation label.
Results
---
🚀
=> (PRODEV-8122) Fix federation validation exit status check

validate-federation/action.yml
Motivation
---
The bypass built into the Validate Federation action isn't functioning on merge.
Modifications
---
Also conditionally validate if the merge_group event has the requisite label for bypass.
Results
---
🚀
=> (PRODEV-8134) Federation Validation merge group label bypass fix

contract-requiring-verification-published-ecr/action.yml
Motivation
---
Pact Verification ran through the webhook is currently failing in BillingAccounting: https://github.com/tesourohq/Tesouro.Payments.Service.BillingAccounting/actions/runs/9507438138/job/26206888987#step:6:1
This is due to the `JOBS_IMAGE` environment variable not being set:
```
env:
AWS_DEFAULT_REGION: us-east-1
AWS_REGION: us-east-1
AWS_ACCESS_KEY_ID: ***
AWS_SECRET_ACCESS_KEY: ***
AWS_SESSION_TOKEN: ***
UNDERTEST_IMAGE: 833624450745.dkr.ecr.us-east-1.amazonaws.com/tesouro/tesouro-service-billingaccounting:latest
PACT_BROKER_TOKEN: ***
PROVIDER_APP_VERSION: 0.1.398
GIT_BRANCH: main
PACT_URL: https://tesouro.pactflow.io/pacts/provider/billingaccounting_service/consumer/reporting_service/pact-version/92fbe3e016ac7a132a1a02a1c60dafc4bd9e992a/metadata/Y3ZuPTAuMS40Ny1wci0wNDAzLjM …
```
=> (PRODEV-8363) Add Jobs Image is a Environment Variable for Pact Verification

functional-tests-ecr/action.yml
Motivation
---
In prep for our move to Github runners in place of BuildJet, we need to have docker-compose installed at the outset of the functional tests.
Modifications
---
I added a step to pull and chmod the docker-compose binary to the runner.
Results
---
functional tests should continue uninterrupted when we switch over to Github runners.
=> (PRODEV-8462) - add step to install docker-compose

contract-requiring-verification-published-ecr/action.yml
Motivation
---
- Ownership of `the-coding-turtle/ga-file-list@v0.4.1` was moved to `martinhaintz/ga-file-list@v0.4.1`
Modifications
---
- Updated location of `ga-file-list` tool
Results
---
- Builds work and such 🚀
=> Update to new home for ga-file-list
