tesourohq/Tesouro-Github-Actions

- get-version/action.yml
Motivation
I want to consume the major.minor.patch version number downstream of this action.
Modifications
I updated the outputs to include this.
> Update outputs to include majorMinorPatch from gitversion.

- build-and-test/action.yml
Motivation
---
we want to start verifying code coverage
Modifications
---
code coverage has been added
Results
---
> add code coverage action

- build-docker-images/action.yml
- functional-tests/action.yml
Motivation
---
- I'd like to build docker images for amd64
Modifications
---
- We'll want to allow us to target arm builds again
> (PAYM-1605) Add Platform as an input

- build-docker-images/action.yml
- functional-tests/action.yml
Motivation
I need some updates to the actions in order to accommodate the use of self-hosted runners.
Modifications
* I updated the way we login to GCR.
> (PAYM-1610) - Use alternative login to GCR.

- armory-deploy/action.yaml
- armory-deploy/example-job.yaml
- build-docker-images/action.yml
- get-version/action.yml
Motivation
I want to reduce the complexity of this action, to make it more flexible for use.
Modifications
I removed all the editing, which will need to be picked up by the microservices as needed, using a combination of `yq` and env vars.
> (PAYM-1913) - Update action to reduce complexity.

- package-and-publish/action.yml
Motivation
---
to not repeat the action code in every repository needing to package/publish a library
Modifications
---
a package & publish action has been added
Results
---
action has been added that other repositories can use
> (PAYM-2158) add package and publish action

- get-version/action.yml
Motivation
I want to use the most recent version of GitVersion.
Modifications
I updated the version.
> (PAYM-2287) - Update GitVersion version.

- armory-deploy/action.yaml
This reverts commit d17731685f4a970c2022d8c5d91e0e32617d9659.
> (PRODEV-1389) Revert my last change

- armory-deploy/action.yaml
Motivation
---
- I'd like to be able to build staging & production database migrations
Modifications
---
- Same as last time BUT with a correct expression
Results
---
- Migrations that work! (well, at least the actions)
> (PRODEV-1389) Re-Add Database Migrations

- functional-tests/action.yml
Motivation
---
If rover is present, we want to wait for it to finish generating the subgraph.
Modifications
---
- Add flag indicating whether rover is running.
- Wait on rover if indicated.
Results
---
Will wait on rover job to finish if present.
> (PRODEV-2039) Wait on rover

- argocd-deploy/action.yaml
Motivation
---
The deployment yaml should not be a fixed path.
Modifications
---
The deployment yaml path is now passed as an input variable.
Results
---
More flexibility.
> [PRODEV-2070] pull out path to deployment yaml as input

- argocd-deploy/action.yaml
Motivation
---
Changed files weren't added on git commit.
Modifications
---
All changed files are added with git commit.
Results
---
Functioning action.
> [PRODEV-2084] Fix git commit

- argocd-deploy/action.yaml
Motivation
---
I want to be able to switch branches on my checkout.
Modifications
---
Set fetch depth to 0.
Results
---
We are able to switch branches.
> [PRODEV-2110] Set fetch depth to 0

- argocd-deploy/action.yaml
Motivation
---
I want ArgoCD deploy to work.
Modifications
---
I set the git config before it's needed.
Results
---
ArgoCD deploy works?
> [PRODEV-2111] set git config first

- argocd-deploy/action.yaml
Motivation
---
We need some way to gate our deployments so that our pipeline doesn't get clobbered.
Modifications
---
I have added main branch locking here so that we can unlock it at the end of deployment.
Results
---
Locked main branch coupled with deployment initialization.
> [PRODEV-2132] Add main branch locking

- argocd-deploy/action.yaml
Motivation
---
I fat fingered my last PR.
Modifications
---
I fixed the errors.
Results
---
It works?
> [PRODEV-2132] update argocd deploy action to lock main branch

- argocd-deploy/action.yaml
Motivation
---
It worked on my machine but not actions.
Modifications
---
I forced it to submit by modifying it until it did.
Results
---
Blessed relief.
> [PRODEV-2141] bug fix argocd deploy action

- argocd-deploy/action.yaml
Motivation
---
I need application semver for a pipeline step.
Modifications
---
I have added a semver label to our kustomize overlays.
Results
---
All resources receive a semver label.
> [PRODEV-2183] add semver label to all manifests

- argocd-deploy/action.yaml
Motivation
---
I need to move semver.
Modifications
---
I moved the semver tag.
Results
---
Semver was moved.
> [PRODEV-2230] move semver

- argocd-deploy/action.yaml
Motivation
---
I want to be absolutely sure we wont have a deployment failure due to db name collisions
Modifications
---
Add optional db name versioning to avoid collisions.
I also removed branch locking from deploy as that will occur as an earlier build step.
> [PRODEV-2254] add db name versioning to avoid collisions

- argocd-deploy/action.yaml
Motivation
---
We have a deployment that doesn't have a service rollout included.
Modifications
---
I have generalized and split out our versioning so that it should work in more cases.
Results
---
ArgoCD Deploy captures more use cases!
> (PRODEV-2782) Generalize and account for non service deployments

- branch-locking/action.yaml
Motivation
---
Let's try keeping DRY.
Modifications
---
Added a branch locking action for more succinct branch locking and unlocking calls.
Results
---
Less noise and more signal!
> (PRODEV-2799) add branch locking GitHub action

- argocd-deploy/action.yaml
Motivation
---
We had some variables that are deprecated in this action.
Modifications
---
I removed app-id and app-pem.
Results
---
👍 ⚡
> (PRODEV-2800) Remove deprecated variables

- build-and-test/action.yml
- package-and-publish/action.yml
Checklist
---
Motivation
---
- So we updated the docker containers.... but not the SDK version specification
- We want the SDK to use 7.0.100 so we're unified across the board
Modifications
---
- Updated SDK usage to 7.0.100
Results
---
- Build should work now (without any changes for source link)
> (PRODEV-3193) Update SDK Defaults for Build

- argocd-deploy/action.yaml
Motivation
---
Modifications
---
- Removed whitespace in git merge command.
Results
---
👍
> (PRODEV-3884) Git merge command fix

- argocd-deploy/action.yaml
Motivation
---
Clean up, simplify, and guarantee deployment.
Modifications
---
- Added 4 bit UID for uniqueness on deploy microservice version.
- Removed deprecated Jobs pattern support.
Results
---
🚀
> (PRODEV-4410) UID refactor

- functional-tests-ecr/action.yml
- functional-tests/action.yml
Motivation
---
Make functional tests work with ECR images.
Modifications
---
Replicated existing functional tests action, modified for ECR instead of GCR. Replicated instead of modified existing action to avoid chicken-egg deployment issues.
Results
---
We now have an action for functional testing with ECR as the image repository.
> (PRODEV-4570) update functional tests action for ECR

- build-docker-images-ecr/action.yml
Motivation
---
We don't want a hardcoded platform.
Modifications
---
Platform is now dependent on the input variable.
Results
---
💪
> (PRODEV-4604) Fix platform passing

- contract-requiring-verification-published-ecr/action.yml
Motivation
---
- We accidentally borked contract validation on many of our microservices
- Example: https://github.com/tesourohq/Tesouro.Payments.Service.Disputes/actions/runs/7010790275/job/19077947850
Modifications
---
- Update to have an ECR friendly contract validation
Results
---
- We should be able to pass contract validation now
> (PRODEV-4724) ECR Friendly Contract Validation

- contract-requiring-verification-published-ecr/action.yml
Motivation
---
- We want contract validations to work
Modifications
---
- Updated to use contract name
Results
---
- Correct image name to be latest (like it was before)
> (PRODEV-4724) Update image name to be accurate for contract testing

- contract-requiring-verification-published-ecr/action.yml
Motivation
---
Minor uplift of new ECR contract verification action.
Modifications
---
- Removed deprecated required var
- Bumped version of docker login action
Results
---
👍
> (PRODEV-4735) Minor var deprecation & login action version bump

- build-docker-images-ecr/action.yml
Quick revert here for the image scanning stuff, until after holidays.
> Revert image scanning

- build-docker-images-ecr/action.yml
This is just an add-back of the work we reverted just before the holidays, so we can debug the issues frontends was having with it. I simplified the implementation a bit, to make troubleshooting easier.
> (PRODEV-5010) - Add back the image scanning action

- federation-validation/action.yml
- validate-federation/action.yml
Motivation
---
Shared action for federation validation.
Modifications
---
- Added Validate Federation action.
Results
---
👍
> (PRODEV-5590) Add federation validation action

- validate-federation/action.yml
Motivation
---
Missed one bug.
Modifications
---
- Fixed the file copy for latest schema test.
Results
---
💪
> (PRODEV-5615) Bug fix validate federation

- validate-federation/action.yml
Motivation
---
Version one of federation validation added value and we want to iterate further with a focus on observability.
Modifications
---
- Added github step summary output from the test federation output.
- Added a graphql diff of the generated supergraphs (diff between deployed and latest including changes in PR)
Results
---
🚀
> (PRODEV-5827) Federation Validation v2

- argocd-deploy/action.yaml
BUGFIX: Update to new session pattern for ArgoCD 2.10
> (PRODEV-5978) - Update argo-deploy pattern to use session token

- argocd-deploy/action.yaml
BUGFIX: Fixes argo deploy action.
> (PRODEV-5978) - Fix argo deploy

- slack-notify/action.yml
- validate-graphql/action.yml
- validate-manifests/action.yml
Motivation
---
Adding some new GHA for consumption.
Modifications
---
- Added Slack-Notify
- Added Validate-Manifest
- Added Validate-GraphQL
Results
---
🚀
> (PRODEV-6547) Uplift Actions - Notify, Validate manifest, Validate GraphQL

- validate-graphql/action.yml
Motivation
---
Suddenly stopped working
Modifications
---
Changed to release tag from commit hash
Results
---
🚀
> (PRODEV-7688) Change from commit hash to release tag for graphql inspector

- build-and-test/action.yml
- common-actions/amazon-ecr-login/action.yml
- common-actions/cache/action.yml
- common-actions/checkout/action.yml
- common-actions/configure-aws-credentials/action.yml
- common-actions/create-pull-request/action.yml
- common-actions/docker-login/action.yml
- common-actions/download-artifact/action.yml
- common-actions/enable-pull-request-automerge/action.yml
- common-actions/github-app-token/action.yml
- common-actions/install-aws-cli/action.yml
- common-actions/setup-dotnet/action.yml
- common-actions/upload-artifact/action.yml
- contract-requiring-verification-published-ecr/action.yml
- create-sdk/action.yml
- functional-tests-ecr/action.yml
- get-version/action.yml
- package-and-publish/action.yml
Motivation
---
We want to be able to control what versions of actions are ran in all the repos, this way we are consistent and don't have to worry about version mismatches causing chaos.
Modifications
---
- Add wrappers for common actions
Results
---
The beginning of full GHA version control!
> (PRODEV-7928) Add wrappers for common actions

- common-actions/install-aws-cli-action/action.yml
- common-actions/upload-artifact/action.yml
- package-and-publish/action.yml
Motivation
---
we need arch
Modifications
---
add arch as arg for install aws cli action
Results
---
arch!
> (PRODEV-7972) Add arch to install aws cli action

- common-actions/github-app-token/action.yml
Motivation
---
-
Modifications
---
_
Results
---
!!!!
> (PRODEV-7976) x-id => x_id

- validate-federation/action.yml
Motivation
---
Validation is still not working as expected.
Modifications
---
Inverse if conditional on status checks
Results
---
🚀
>  (PRODEV-8135) Federation Validation bug fix

- validate-federation/action.yml
Motivation
---
Federation validation if conditional didn't expand as expected.
Modifications
---
Moved not to not equals.
Results
---
🚀 🤞
> (PRODEV-8171) Federation Validation conditional fix

- common-actions/create-pull-request/action.yml
- common-actions/github-app-token/action.yml
Motivation
---
[workflow](https://github.com/tesourohq/Tesouro.Payments.Frontends/actions/runs/9389038862/job/25904249186) broken on frontend that auto generates a PR
Modifications
---
add in output. frontends was not getting the token output (still unclear as to how this is working elsewhere). also, add in some inputs that frontends was using
Results
---
working "sync graphql schema" workflow in frontends
> (PRODEV-7928) add in inputs for creating a PR

- build-docker-images-ecr/.trivyignores
Motivation
---
https://github.com/tesourohq/Tesouro.Payments.Service.Reporting/actions/runs/9598700027/attempts/1#summary-26470695903
Modifications
---
- ignore this CVE till the end of the month - hopefully LB has a fixed version by then.
Results
---
🫐
> (PRODEV-8378) Ignore CVE-2024-24790 for a little while

- argocd-deploy/action.yaml
Motivation
---
If the call to sync fails it still shows as a good run.
Modifications
---
- read response and report failure to sync
Results
---
Information!
> (PRODEV-8551) Propagate failures to sync

- cosmo-graphql-check/action.yml
- validate-subgraph-graphql/action.yml
Motivation
---
Integrate Cosmo graphql checks
Modifications
---
- Add action for running checks against staging and production namespaces.
Results
---
🚀
> (PRODEV-9107) Add cosmo graphql check action
